version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: jakarta-mongodb
    environment:
      - MONGO_INITDB_DATABASE=jakarta_traffic
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: