pipeline:
  name: test_pipeline
  options:
    queue_monitor_delay_seconds: 10
    queue_monitor_meter_size: 10
  tasks:
  - file_regex: .*\.mp4
    name: readVid
    num_workers: 1
    output_queue_size: 100
    prev_task: null
    vid_dir: downloaded_videos
    worker_type: ReadFramesFromVidFilesInDir
  - log_level: INFO
    log_sample_interval: 20
    log_values: true
    name: logKeysAfterRead
    num_workers: 1
    output_queue_size: 100
    prev_task: readVid
    worker_type: LogAllKeys
  - annotate_result_frame_key: boxed_frame
    buffer_size: 100
    class_nonzero_threshold: 0.4
    frame_key: frame
    gpu: 0
    gpu_share: 0.9
    name: objectDetect
    non_maximal_box_suppression: true
    non_maximal_box_suppression_threshold: 0.4
    num_workers: 1
    object_detect_threshold: 0.4
    output_queue_size: 120
    prev_task: logKeysAfterRead
    weights_path: models/yolo11m.pt
    worker_type: Yolo3Detect
  - log_level: INFO
    log_sample_interval: 20
    log_values: true
    name: logKeysAfterDetect
    num_workers: 1
    output_queue_size: 100
    prev_task: objectDetect
    worker_type: LogAllKeys
  - annotate_frame_key: boxed_frame
    annotate_result_frame_key: pathed_frame
    backward_pass: false
    bg_mask_key: null
    blockSize: 7
    frame_key: frame
    good_flow_difference_threshold: 1
    how_many_track_new_points_before_clearing_points: 30
    maxCorners: 500
    maxLevel: 3
    minDistance: 7
    name: motionDetect
    new_point_detect_interval: null
    new_point_detect_interval_per_second: 5
    new_point_occlusion_radius: 5
    num_workers: 1
    output_queue_size: 100
    prev_task: logKeysAfterDetect
    qualityLevel: 0.3
    rename_outputs:
      flows: tracked_flows
      points: tracked_points
    winSize:
    - 20
    - 20
    worker_type: LKSparseOpticalFlow
  - log_level: INFO
    log_sample_interval: 20
    log_values: true
    name: logKeysAfterMotion
    num_workers: 1
    output_queue_size: 100
    prev_task: motionDetect
    worker_type: LogAllKeys
  - annotate_result_frame_key: mean_motion
    mapping:
      points_grouped_by_box:
        0: box_id
        1: point_count
        2: avg_motion_x
        3: avg_motion_y
        4: motion_magnitude
        6: motion_direction
    name: meanMotion
    num_workers: 1
    output_queue_size: 100
    prev_task: logKeysAfterMotion
    stationary_threshold: 1
    worker_type: MeanMotionDirection
  - log_level: INFO
    log_sample_interval: 20
    log_values: true
    name: logKeysAfterMeanMotion
    num_workers: 1
    output_queue_size: 100
    prev_task: meanMotion
    worker_type: LogAllKeys
  - additional_data:
    - box_id
    buffer_size: 50
    columns:
    - video_id
    - frame_number
    - box_id
    - class_name
    - confidence
    - x1
    - y1
    - x2
    - y2
    field_separator: "\t"
    keys:
    - boxes
    name: writeBoxesDB
    num_workers: 1
    output_queue_size: null
    prev_task: objectDetect
    schemas:
    - mongodb
    tables:
    - boxes
    transforms:
      boxes:
        format: '{video_id},{frame_number},{box_id},{class_name},{confidence},{x1},{y1},{x2},{y2}'
    worker_type: WriteKeysToDatabaseTable
  - additional_data:
    - box_id
    buffer_size: 50
    columns:
    - video_id
    - frame_number
    - box_id
    - num_points
    - mean_dx
    - mean_dy
    - magnitude
    - angle_degrees
    field_separator: "\t"
    keys:
    - points_grouped_by_box
    name: writeMotionDB
    num_workers: 1
    output_queue_size: null
    prev_task: meanMotion
    schemas:
    - mongodb
    tables:
    - box_motion
    transforms:
      points_grouped_by_box:
        format: '{video_id},{frame_number},{box_id},{num_points},{mean_dx},{mean_dy},{magnitude},{angle_degrees}'
    worker_type: WriteKeysToDatabaseTable
  - buffer_size: 100
    frame_key: boxed_frame
    name: writeBoxedFrameVid
    num_workers: 1
    output_queue_size: null
    prev_task: logKeysAfterDetect
    worker_type: WriteFramesToVidFiles
  - buffer_size: 100
    frame_key: pathed_frame
    name: writePathedFrameVid
    num_workers: 1
    output_queue_size: null
    prev_task: logKeysAfterMotion
    worker_type: WriteFramesToVidFiles
