pipeline:
    name: test_pipeline
    tasks:  # The list of tasks which create the Directed Acyclic Graph of tasks in this task list. See each class for descriptions of the parameters
        - worker_type: ReadFramesFromVidFilesInDir
          name: readVid
          prev_task: 
          num_workers: 1
          output_queue_size: 100
          vid_dir: # directory where input videos exist
          file_regex: ^Pluit(.*).mkv  # regular expression which matches correspond to desired input files. 
        - worker_type: Yolo3Detect
          name: objectDetect
          prev_task: readVid
          num_workers: 1
          output_queue_size: 120
          buffer_size: 100
          gpu: 0
          gpu_share: 0.9
          weights_path: /path/to/weights/file.weights
          frame_key: frame
          annotate_result_frame_key: boxed_frame
          object_detect_threshold: 0.4
          class_nonzero_threshold: 0.4
          non_maximal_box_suppression: True
          non_maximal_box_suppression_threshold: 0.4
        - worker_type: LKSparseOpticalFlow
          name: motionDetect
          prev_task: objectDetect
          num_workers: 1
          output_queue_size: 100
          frame_key: frame
          annotate_frame_key: frame
          annotate_result_frame_key: pathed_frame
          backward_pass: False
          new_point_detect_interval: ~
          new_point_detect_interval_per_second: 5
          how_many_track_new_points_before_clearing_points: 30
          new_point_occlusion_radius: 5
          good_flow_difference_threshold: 1
          bg_mask_key:
          winSize: [20, 20]
          maxLevel: 3
          maxCorners: 500
          qualityLevel: 0.3
          minDistance: 7
          blockSize: 7
        - worker_type: MeanMotionDirection
          name: meanMotion
          prev_task: motionDetect
          num_workers: 1
          output_queue_size: 100
          annotate_result_frame_key: mean_motion
          stationary_threshold: 1  # pixels
        - worker_type: WriteKeysToDatabaseTable
          name: writeBoxesDB
          prev_task: objectDetect
          num_workers: 1
          buffer_size: 50
          output_queue_size: ~
          keys: [boxes]
          keys_headers: [boxes_header]
          additional_data: [box_id]
          schemas: [results]
          tables: [boxes]
          field_separator: "\t"
        - worker_type: WriteKeysToDatabaseTable
          name: writeMotionDB
          prev_task: meanMotion
          num_workers: 1
          buffer_size: 50
          output_queue_size: ~
          keys: [points_grouped_by_box]
          keys_headers: [points_grouped_by_box_header]
          additional_data: [box_id]
          schemas: [results]
          tables: [box_motion]
          field_separator: "\t"
        - worker_type: WriteFramesToVidFiles
          name: writeVid
          prev_task: objectDetect
          num_workers: 1
          buffer_size: 1500
          output_queue_size: ~
          frame_key: "boxed_frame"
        - worker_type: WriteFramesToVidFiles
          name: writeVid
          prev_task: motionDetect
          num_workers: 1
          buffer_size: 1500
          output_queue_size: ~
          frame_key: "pathed_frame"
    options: # options for the queue visualization in the printed output
        queue_monitor_meter_size: 10  # size of the meters
        queue_monitor_delay_seconds: 10  # how long to wait between printing the queues. 
