pipeline:
  name: motorcycle_sidewalk_detection
  options:
    queue_monitor_delay_seconds: 10
    queue_monitor_meter_size: 10
  tasks:
  - file_regex: .*\.mp4
    name: readVid
    num_workers: 1
    output_queue_size: 100
    prev_task: null
    vid_dir: downloaded_videos
    worker_type: ReadFramesFromVidFilesInDir
  - annotate_result_frame_key: boxed_frame
    buffer_size: 100
    class_nonzero_threshold: 0.4
    frame_key: frame
    gpu: 0
    gpu_share: 0.9
    name: objectDetect
    non_maximal_box_suppression: true
    non_maximal_box_suppression_threshold: 0.4
    num_workers: 1
    object_detect_threshold: 0.4
    output_queue_size: 120
    prev_task: readVid
    weights_path: models/yolo11m-seg.pt  # Use YOLOv11m model with segmentation
    sidewalk_overlap_threshold: 0.3  # The minimum overlap to classify as "on sidewalk"
    worker_type: Yolo11mSegDetect
  - annotate_frame_key: boxed_frame
    annotate_result_frame_key: pathed_frame
    backward_pass: false
    bg_mask_key: null
    blockSize: 7
    frame_key: frame
    good_flow_difference_threshold: 1
    how_many_track_new_points_before_clearing_points: 30
    maxCorners: 500
    maxLevel: 3
    minDistance: 7
    name: motionDetect
    new_point_detect_interval: null
    new_point_detect_interval_per_second: 5
    new_point_occlusion_radius: 5
    num_workers: 1
    output_queue_size: 100
    prev_task: objectDetect
    qualityLevel: 0.3
    winSize:
    - 20
    - 20
    worker_type: LKSparseOpticalFlow

  - file_regex: (.+)\.mp4
    frame_key: pathed_frame
    name: writeVid
    num_workers: 1
    output_dir: outputs/violations
    output_queue_size: 100
    prev_task: motionDetect
    worker_type: WriteFramesToVidFiles
